### ISSUE TITLE
Sample Test in Docs Fails

### ISSUE THREAD

**Issue by bhorowitz** [steven-murray/hmf#2]
I downloaded the latest hmf version (using "pip install hmf") and tried to run the sample script given in the help documents (http://hmf.readthedocs.org/en/latest/):

from hmf import MassFunction
hmf = MassFunction()
mass_func = hmf.dndlnm

The last line returns a type error that I cannot seem to diagnose; output below. 

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-33-cb204c2f7656> in <module>()
      1 from hmf import MassFunction
      2 hmf = MassFunction()
----> 3 mass_func = hmf.dndlnm
      4 mass_variance = hmf.sigma

/Library/Python/2.7/site-packages/hmf/_cache.pyc in _get_property(self)
     50             # If recalc is constructed, and it needs to be updated, recalculate
     51             if getattr(self, recalc).get(name, True):
---> 52                 value = f(self)
     53                 setattr(self, prop, value)
     54 

/Library/Python/2.7/site-packages/hmf/hmf.pyc in dndlnm(self)
    372         The differential mass function in terms of natural log of `M`, ``len=len(M)`` [units :math:`h^3 Mpc^{-3}`]
    373         """
--> 374         return self.M * self.dndm
    375 
    376     @cached_property("M", "dndm")

/Library/Python/2.7/site-packages/hmf/_cache.pyc in _get_property(self)
     50             # If recalc is constructed, and it needs to be updated, recalculate
     51             if getattr(self, recalc).get(name, True):
---> 52                 value = f(self)
     53                 setattr(self, prop, value)
     54 

/Library/Python/2.7/site-packages/hmf/hmf.pyc in dndm(self)
    335         """
    336         if self.z2 is None:  # #This is normally the case
--> 337             dndm = self.fsigma * self.mean_dens * np.abs(self._dlnsdlnm) / self.M ** 2
    338             if isinstance(self._fit, Behroozi):
    339                 ngtm_tinker = self._gtm(dndm)

/Library/Python/2.7/site-packages/hmf/_cache.pyc in _get_property(self)
     50             # If recalc is constructed, and it needs to be updated, recalculate
     51             if getattr(self, recalc).get(name, True):
---> 52                 value = f(self)
     53                 setattr(self, prop, value)
     54 

/Library/Python/2.7/site-packages/hmf/hmf.pyc in fsigma(self)
    318         The multiplicity function, :math:`f(\sigma)`, for `mf_fit`. ``len=len(M)``
    319         """
--> 320         fsigma = self._fit.fsigma(self.cut_fit)
    321 
    322         if np.sum(np.isnan(fsigma)) > 0.8 * len(fsigma):

/Library/Python/2.7/site-packages/hmf/_cache.pyc in _get_property(self)
     50             # If recalc is constructed, and it needs to be updated, recalculate
     51             if getattr(self, recalc).get(name, True):
---> 52                 value = f(self)
     53                 setattr(self, prop, value)
     54 

/Library/Python/2.7/site-packages/hmf/hmf.pyc in _fit(self)
    233             fit = self.mf_fit(self)
    234         except:
--> 235             fit = get_fit(self.mf_fit, self)
    236         return fit
    237 

/Library/Python/2.7/site-packages/hmf/fitting_functions.pyc in get_fit(name, h)
     15     """
     16     try:
---> 17         return getattr(sys.modules[__name__], name)(h)
     18     except AttributeError:
     19         raise AttributeError(str(name) + "  is not a valid FittingFunction class")

TypeError: getattr(): attribute name must be string

**Comment by steven-murray** [comment]
I'm going to close this because there's been no activity for a while and I can't reproduce the error, but please let me know if it persists.

**Comment by boada** [comment]
I am getting the same error. Installed from PIP. 

In [10]: hmf.dndm
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-10-00c39dae30fe> in <module>()
----> 1 hmf.dndm

/opt/python/lib/python2.7/site-packages/hmf/_cache.pyc in _get_property(self)
     50             # If recalc is constructed, and it needs to be updated, recalculate
     51             if getattr(self, recalc).get(name, True):
---> 52                 value = f(self)
     53                 setattr(self, prop, value)
     54

/opt/python/lib/python2.7/site-packages/hmf/hmf.pyc in how_big(self)
    516         """
    517
--> 518         return self.ngtm ** (-1. / 3.)

/opt/python/lib/python2.7/site-packages/hmf/_cache.pyc in _get_property(self)
     50             # If recalc is constructed, and it needs to be updated, recalculate
     51             if getattr(self, recalc).get(name, True):
---> 52                 value = f(self)
     53                 setattr(self, prop, value)
     54

/opt/python/lib/python2.7/site-packages/hmf/hmf.pyc in ngtm(self)
    467         appropriate mass ranges in this case.
    468         """
--> 469         return self._gtm(self.dndm)
    470
    471     @cached_property("M", "dndm")

/opt/python/lib/python2.7/site-packages/hmf/_cache.pyc in _get_property(self)
     50             # If recalc is constructed, and it needs to be updated, recalculate
     51             if getattr(self, recalc).get(name, True):
---> 52                 value = f(self)
     53                 setattr(self, prop, value)
     54

/opt/python/lib/python2.7/site-packages/hmf/hmf.pyc in dndm(self)
    362         """
    363         if self.z2 is None:  # #This is normally the case
--> 364             dndm = self.fsigma * self.mean_dens * np.abs(self._dlnsdlnm) / self.M ** 2
    365             if isinstance(self._fit, Behroozi):
    366                 ngtm_tinker = self._gtm(dndm)

/opt/python/lib/python2.7/site-packages/hmf/_cache.pyc in _get_property(self)
     50             # If recalc is constructed, and it needs to be updated, recalculate
     51             if getattr(self, recalc).get(name, True):
---> 52                 value = f(self)
     53                 setattr(self, prop, value)
     54

/opt/python/lib/python2.7/site-packages/hmf/hmf.pyc in fsigma(self)
    345         The multiplicity function, :math:`f(\sigma)`, for `mf_fit`. ``len=len(M)``
    346         """
--> 347         fsigma = self._fit.fsigma(self.cut_fit)
    348
    349         if np.sum(np.isnan(fsigma)) > 0.8 * len(fsigma):

/opt/python/lib/python2.7/site-packages/hmf/_cache.pyc in _get_property(self)
     50             # If recalc is constructed, and it needs to be updated, recalculate
     51             if getattr(self, recalc).get(name, True):
---> 52                 value = f(self)
     53                 setattr(self, prop, value)
     54

/opt/python/lib/python2.7/site-packages/hmf/hmf.pyc in _fit(self)
    257                               ** self._fsig_params)
    258         except TypeError:
--> 259             fit = get_fit(self.mf_fit, M=self.M, nu2=self.nu, z=self.z,
    260                           delta_halo=self.delta_halo, omegam_z=self.omegam_z,
    261                           delta_c=self.delta_c, sigma=self.sigma, n_eff=self.n_eff,

/opt/python/lib/python2.7/site-packages/hmf/_cache.pyc in _get_property(self)
     50             # If recalc is constructed, and it needs to be updated, recalculate
     51             if getattr(self, recalc).get(name, True):
---> 52                 value = f(self)
     53                 setattr(self, prop, value)
     54

/opt/python/lib/python2.7/site-packages/hmf/hmf.pyc in nu(self)
    324         The parameter :math:`\nu = \left(\frac{\delta_c}{\sigma}\right)^2`, ``len=len(M)``
    325         """
--> 326         return (self.delta_c / self.sigma) ** 2
    327
    328     @cached_property("sigma")

/opt/python/lib/python2.7/site-packages/hmf/_cache.pyc in _get_property(self)
     50             # If recalc is constructed, and it needs to be updated, recalculate
     51             if getattr(self, recalc).get(name, True):
---> 52                 value = f(self)
     53                 setattr(self, prop, value)
     54

/opt/python/lib/python2.7/site-packages/hmf/hmf.pyc in sigma(self)
    317         The mass variance at `z`, ``len=len(M)``
    318         """
--> 319         return self._sigma_0 * self.growth
    320
    321     @cached_property("sigma", "delta_c")

/opt/python/lib/python2.7/site-packages/hmf/_cache.pyc in _get_property(self)
     50             # If recalc is constructed, and it needs to be updated, recalculate
     51             if getattr(self, recalc).get(name, True):
---> 52                 value = f(self)
     53                 setattr(self, prop, value)
     54

/opt/python/lib/python2.7/site-packages/hmf/hmf.pyc in _sigma_0(self)
    293
    294         """
--> 295         return tools.mass_variance(self.M, self._lnP_0,
    296                                    self.lnk,
    297                                    self.mean_dens, "trapz")

/opt/python/lib/python2.7/site-packages/hmf/_cache.pyc in _get_property(self)
     50             # If recalc is constructed, and it needs to be updated, recalculate
     51             if getattr(self, recalc).get(name, True):
---> 52                 value = f(self)
     53                 setattr(self, prop, value)
     54

/opt/python/lib/python2.7/site-packages/hmf/transfer.pyc in _lnP_0(self)
    411                                       self.lnk, self.h, self.omegac)
    412         else:
--> 413             return self._lnP_cdm_0
    414
    415

/opt/python/lib/python2.7/site-packages/hmf/_cache.pyc in _get_property(self)
     50             # If recalc is constructed, and it needs to be updated, recalculate
     51             if getattr(self, recalc).get(name, True):
---> 52                 value = f(self)
     53                 setattr(self, prop, value)
     54

/opt/python/lib/python2.7/site-packages/hmf/transfer.pyc in _lnP_cdm_0(self)
    390         """
    391         return tools.normalize(self.sigma_8,
--> 392                                self._unnormalised_lnP,
    393                                self.lnk, self.mean_dens)[0]
    394

/opt/python/lib/python2.7/site-packages/hmf/_cache.pyc in _get_property(self)
     50             # If recalc is constructed, and it needs to be updated, recalculate
     51             if getattr(self, recalc).get(name, True):
---> 52                 value = f(self)
     53                 setattr(self, prop, value)
     54

/opt/python/lib/python2.7/site-packages/hmf/transfer.pyc in _unnormalised_lnP(self)
    382         Un-normalised CDM log power at :math:`z=0` [units :math:`Mpc^3/h^3`]
    383         """
--> 384         return self.n * self.lnk + 2 * self._unnormalised_lnT
    385
    386     @cached_property("sigma_8", "_unnormalised_lnP", "lnk", "mean_dens")

/opt/python/lib/python2.7/site-packages/hmf/_cache.pyc in _get_property(self)
     50             # If recalc is constructed, and it needs to be updated, recalculate
     51             if getattr(self, recalc).get(name, True):
---> 52                 value = f(self)
     53                 setattr(self, prop, value)
     54

/opt/python/lib/python2.7/site-packages/hmf/transfer.pyc in _unnormalised_lnT(self)
    375             return self.transfer_fit(self).lnt(self.lnk)
    376         except:
--> 377             return get_transfer(self.transfer_fit, self).lnt(self.lnk)
    378
    379     @cached_property("n", "lnk", "_unnormalised_lnT")

/opt/python/lib/python2.7/site-packages/hmf/transfer.pyc in get_transfer(name, t)
     29     """
     30     try:
---> 31         return getattr(sys.modules[__name__], name)(t)
     32     except AttributeError:
     33         raise AttributeError(str(name) + "  is not a valid GetTransfer class")

TypeError: getattr(): attribute name must be string

**Comment by boada** [comment]
After installing the github version... 

In [4]: hmf = MassFunction()
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-6174d33df13f> in <module>()
----> 1 hmf = MassFunction()

/opt/python/lib/python2.7/site-packages/hmf-1.8.0-py2.7.egg/hmf/hmf.pyc in __init__(self, Mmin, Mmax, dlog10m, mf_fit, delta_h, delta_wrt, cut_fit, z2, nz, _fsig_params, delta_c, filter, filter_params, **transfer_kwargs)
    123         """
    124         # # Call super init MUST BE DONE FIRST.
--> 125         super(MassFunction, self).__init__(**transfer_kwargs)
    126
    127         # Set all given parameters.

/opt/python/lib/python2.7/site-packages/hmf-1.8.0-py2.7.egg/hmf/transfer.pyc in __init__(self, z, lnk_min, lnk_max, dlnk, transfer_fit, transfer_options, takahashi, **kwargs)
    274         self.dlnk = dlnk
    275         self.z = z
--> 276         self.transfer_fit = transfer_fit
    277         self.transfer_options = transfer_options
    278         self.takahashi = takahashi

/opt/python/lib/python2.7/site-packages/hmf-1.8.0-py2.7.egg/hmf/_cache.pyc in _set_property(self, val)
    160     def _set_property(self, val):
    161         prop = ("_" + self.__class__.__name__ + prop_ext).replace("___", "__")
--> 162         val = f(self, val)
    163         try:
    164             old_val = getattr(self, prop)

/opt/python/lib/python2.7/site-packages/hmf-1.8.0-py2.7.egg/hmf/transfer.pyc in transfer_fit(self, val)
    347     def transfer_fit(self, val):
    348         if not HAVE_PYCAMB and (val == "CAMB" or val == CAMB):
--> 349             raise ValueError("You cannot use the CAMB transfer since pycamb isn't installed")
    350         if not (issubclass_(val, GetTransfer) or isinstance(val, basestring)):
    351             raise ValueError("transfer_fit must be string or GetTransfer subclass")

ValueError: You cannot use the CAMB transfer since pycamb isn't installed

**Comment by steven-murray** [comment]
Hi, it looks like I need to update the pypi version to reflect the bugfixes
made in more recent commits.

Your second error arises because you have not installed pycamb (please
follow instructions on hmf.readthedocs.org). Alternatively,  you can set
`transfer_fit="EH"` in the constructor.

Cheers
Steven

**Comment by boada** [comment]
hmf.readthedocs.org says pyCAMB is an optional install. It sounds like that is no longer the case.

=)

**Comment by steven-murray** [comment]
Hi Steven,

Ah I'll have to update the docs to be clearer!  It is in fact still
optional but the hard wired default is to use CAMB so it will by default
give an error of its not installed. In that case you have to manually
specify a different fit.

**Comment by steven-murray** [comment]
This is fixed in the newest version 2.0.0

**Comment by boada** [comment]
The [read the docs](http://hmf.readthedocs.org/en/latest/) site still has this sentence: 

> The final, optional, library is pycamb, which can not be installed using pip currently.

Which gives me the idea that pycamb is still not required. So if you follow the Quick Start guide, and don't change `transfer_fit="EH"` in the constructor, then it will still throw an error?

**Comment by steven-murray** [comment]
Hi,
I'm fairly confident that the default should be automatically set based on whether pycamb is installed in v2.0.0. Please let me know if that's not the case!
